export enum BungieMembershipType {
    None = 0,
    TigerXbox = 1,
    TigerPsn = 2,
    TigerSteam = 3,
    TigerBlizzard = 4,
    TigerStadia = 5,
    TigerEgs = 6,
    TigerDemon = 10,
    GoliathGame = 20,
    BungieNext = 254,
    All = -1,
}

export enum DestinyProgressionRewardItemState {
    None = 0,
    Invisible = 1,
    Earned = 2,
    Claimed = 4,
    ClaimAllowed = 8,
}

export enum DestinyStatAggregationType {
    CharacterAverage = 0,
    Character = 1,
    Item = 2,
}

export enum DestinyStatCategory {
    Gameplay = 0,
    Weapon = 1,
    Defense = 2,
    Primary = 3,
}

export enum ItemState {
    None = 0,
    Locked = 1,
    Tracked = 2,
    Masterwork = 4,
    Crafted = 8,
    HighlightedObjective = 16,
}

export enum DestinyProgressionScope {
    Account = 0,
    Character = 1,
    Clan = 2,
    Item = 3,
    ImplicitFromEquipment = 4,
    Mapped = 5,
    MappedAggregate = 6,
    MappedStat = 7,
    MappedUnlockValue = 8,
}

export enum DestinyProgressionStepDisplayEffect {
    None = 0,
    Character = 1,
    Item = 2,
}

export enum SocketTypeActionType {
    InsertPlug = 0,
    InfuseItem = 1,
    ReinitializeSocket = 2,
}

export enum DestinySocketVisibility {
    Visible = 0,
    Hidden = 1,
    HiddenWhenEmpty = 2,
    HiddenIfNoPlugsAvailable = 3,
}

export enum DestinySocketCategoryStyle {
    Unknown = 0,
    Reusable = 1,
    Consumable = 2,
    Unlockable = 3,
    Intrinsic = 4,
    EnergyMeter = 5,
    LargePerk = 6,
    Abilities = 7,
    Supers = 8,
}

export enum DestinyActivityModeType {
    None = 0,
    Story = 2,
    Strike = 3,
    Raid = 4,
    "All PvP" = 5,
    Patrol = 6,
    "All PvE" = 7,
    Reserved9 = 9,
    Control = 10,
    Reserved11 = 11,
    Clash = 12,
    Reserved13 = 13,
    "Crimson Doubles" = 15,
    Nightfall = 16,
    "Heroic Nightfall" = 17,
    "All Strikes" = 18,
    "Iron Banner" = 19,
    Reserved20 = 20,
    Reserved21 = 21,
    Reserved22 = 22,
    Reserved24 = 24,
    "All Mayhem" = 25,
    Reserved26 = 26,
    Reserved27 = 27,
    Reserved28 = 28,
    Reserved29 = 29,
    Reserved30 = 30,
    Supremacy = 31,
    "Private Matches All" = 32,
    Survival = 37,
    Countdown = 38,
    "Trials Of The Nine" = 39,
    Social = 40,
    "Trials Countdown" = 41,
    "Trials Survival" = 42,
    "Iron Banner Control" = 43,
    "Iron Banner Clash" = 44,
    "Iron Banner Supremacy" = 45,
    "Scored Nightfall" = 46,
    "Scored Heroic Nightfall" = 47,
    Rumble = 48,
    "All Doubles" = 49,
    Doubles = 50,
    "Private Matches Clash" = 51,
    "Private Matches Control" = 52,
    "Private Matches Supremacy" = 53,
    "Private Matches Countdown" = 54,
    "Private Matches Survival" = 55,
    "Private Matches Mayhem" = 56,
    "Private Matches Rumble" = 57,
    "Heroic Adventure" = 58,
    Showdown = 59,
    Lockdown = 60,
    Scorched = 61,
    "Scorched Team" = 62,
    Gambit = 63,
    "All PvE Competitive" = 64,
    Breakthrough = 65,
    "Black Armory Run" = 66,
    Salvage = 67,
    "Iron Banner Salvage" = 68,
    "PvP Competitive" = 69,
    "PvP Quickplay" = 70,
    "Clash Quickplay" = 71,
    "Clash Competitive" = 72,
    "Control Quickplay" = 73,
    "Control Competitive" = 74,
    "Gambit Prime" = 75,
    "Reckoning" = 76,
    "Menagerie" = 77,
    "Vex Offensive" = 78,
    "Nightmare Hunt" = 79,
    "Elimination" = 80,
    "Momentum" = 81,
    "Dungeon" = 82,
    "Sundial" = 83,
    "Trials Of Osiris" = 84,
    "Dares" = 85,
    "Offensive" = 86,
    "Lost Sector" = 87,
    "Rift" = 88,
    "Zone Control" = 89,
    "Iron Banner Rift" = 90,
    "Iron Banner Zone Control" = 91,
    "Relic" = 92,
}
